config/routes.rb
EchoBest::Application.routes.draw do

  resources :auths

	resources :user

end

app/models/auth.rb
class Auth < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
  before_action :set_auth, only: [:show, :edit, :update, :destroy]

  # GET /auths
  # GET /auths.json
  def index
    @auths = Auth.all
  end

  # GET /auths/1
  # GET /auths/1.json
  def show
  end

  # GET /auths/new
  def new
    @auth = Auth.new
  end

  # GET /auths/1/edit
  def edit
  end

  # POST /auths
  # POST /auths.json
  def create
    @auth = Auth.new(auth_params)

    respond_to do |format|
      if @auth.save
        format.html { redirect_to @auth, notice: 'Auth was successfully created.' }
        format.json { render action: 'show', status: :created, location: @auth }
      else
        format.html { render action: 'new' }
        format.json { render json: @auth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auths/1
  # PATCH/PUT /auths/1.json
  def update
    respond_to do |format|
      if @auth.update(auth_params)
        format.html { redirect_to @auth, notice: 'Auth was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @auth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auths/1
  # DELETE /auths/1.json
  def destroy
    @auth.destroy
    respond_to do |format|
      format.html { redirect_to auths_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auth
      @auth = Auth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auth_params
      params.require(:auth).permit(:auth_name, :password_digest, :token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auths/_form.html.erb
<%= form_for(@auth) do |f| %>
  <% if @auth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auth.errors.count, "error") %> prohibited this auth from being saved:</h2>

      <ul>
      <% @auth.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :auth_name %><br>
    <%= f.text_field :auth_name %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :token %><br>
    <%= f.text_field :token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/auths/edit.html.erb
<h1>Editing auth</h1>

<%= render 'form' %>

<%= link_to 'Show', @auth %> |
<%= link_to 'Back', auths_path %>

app/views/auths/index.html.erb
<h1>Listing auths</h1>

<table>
  <thead>
    <tr>
      <th>Auth name</th>
      <th>Password digest</th>
      <th>Token</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @auths.each do |auth| %>
      <tr>
        <td><%= auth.auth_name %></td>
        <td><%= auth.password_digest %></td>
        <td><%= auth.token %></td>
        <td><%= link_to 'Show', auth %></td>
        <td><%= link_to 'Edit', edit_auth_path(auth) %></td>
        <td><%= link_to 'Destroy', auth, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auth', new_auth_path %>

app/views/auths/new.html.erb
<h1>New auth</h1>

<%= render 'form' %>

<%= link_to 'Back', auths_path %>

app/views/auths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Auth name:</strong>
  <%= @auth.auth_name %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @auth.password_digest %>
</p>

<p>
  <strong>Token:</strong>
  <%= @auth.token %>
</p>

<%= link_to 'Edit', edit_auth_path(@auth) %> |
<%= link_to 'Back', auths_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EchoBest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>